apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ag.name" . }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
  MAPPING_RULES_PATH: /app/config/mapping-rules.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ag.name" . }}-rules
data:
  mapping-rules.yaml: |
    {{- toYaml .Values.mappingRules | nindent 4 }}
