apiVersion: v1
kind: Service
metadata:
  name: {{ include "ag.name" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: web
    {{- include "ag.labels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
